### ISSUE TITLE
unable to add more vertex columns

### ISSUE THREAD

**Issue by manandakrishna** [lordlinus/cosmosdb-graphql#1]
Hello team,

I am deployed the code it is working only for "ID","partition name","label" columns. I have additional columns(properties) of the vertext to be added. I tried to add two more columns
vertex_properties_col_name=[formula_master["formula_name"], formula_master["formula_type"]], when execute job, below error is coming "unable to resolve new columns"

 Resolved attribute(s) formula_name#910,formula_type#911 missing from id#1755,chrd2#1761,label#1764 in operator !Pro

can you please help?

regards
Anand M

**Comment by lordlinus** [comment]
@manandakrishna sorry for late response. can you take a look at https://github.com/lordlinus/cosmosdb-graph-demo/blob/main/load_data/Load_Airportsgraphdatasample.ipynb notebook
